//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poligons2D
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cercle
    {
        public int Id { get; set; }
        public Nullable<int> Radi { get; set; }
    
        public virtual Poligon Poligon { get; set; }
    }
}
