//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poligons2D
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Poligons2DEntities : DbContext
    {
        public Poligons2DEntities()
            : base("name=Poligons2DEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cercle> Cercle { get; set; }
        public virtual DbSet<Elipse> Elipse { get; set; }
        public virtual DbSet<Hexagon> Hexagon { get; set; }
        public virtual DbSet<Octogon> Octogon { get; set; }
        public virtual DbSet<Pentagon> Pentagon { get; set; }
        public virtual DbSet<Poligon> Poligon { get; set; }
        public virtual DbSet<Quadrats> Quadrats { get; set; }
        public virtual DbSet<Rombre> Rombre { get; set; }
        public virtual DbSet<Triangle> Triangle { get; set; }
    }
}
