//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poligons2D
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poligon
    {
        public int Id { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Color { get; set; }
        public Nullable<bool> TeInterior { get; set; }
        public string TipusPoligon { get; set; }
    
        public virtual Cercle Cercle { get; set; }
        public virtual Elipse Elipse { get; set; }
        public virtual Hexagon Hexagon { get; set; }
        public virtual Octogon Octogon { get; set; }
        public virtual Pentagon Pentagon { get; set; }
        public virtual Quadrats Quadrats { get; set; }
        public virtual Rombre Rombre { get; set; }
        public virtual Triangle Triangle { get; set; }
    }
}
